directories:
  output: release
  buildResources: build
appId: com.yourname.clipboard-manager
productName: Clipboard Manager
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - node_modules/**/*
mac:
  category: public.app-category.productivity
  target: dmg
  icon: assets/icon.icns
  darkModeSupport: true
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
win:
  target: nsis
  icon: assets/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 30.5.1
